version: '3.4'

services:

  # webfront http server
  ps:
    tty: true # allows log to stdout
    build: ./docker/prestashop
    ports:
      - 8080:80  # for external access
      - 8443:443 # for external access
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: ps_user
      DB_PASSWD: ${GLOBAL_MYSQL_PASSWORD}
      #
      PS_ENABLE_SSL: 1
      #
      PS_DEMO_MODE: 1
      # install mode - dangerous
      # PS_INSTALL_DB: 1
      # PS_ERASE_DB: 1
      # PS_INSTALL_AUTO: 1
      #
      PS_COUNTRY: FR
      PS_LANGUAGE: fr
      ADMIN_MAIL: demo@prestashop.com
      ADMIN_PASSWD: prestashop_demo

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      # reuse variables define above
      MYSQL_DATABASE: prestashop
      MYSQL_USER: ps_user
      MYSQL_PASSWORD: ${GLOBAL_MYSQL_PASSWORD}
    healthcheck:
        test: ["CMD", "bash",  "-c",  "[ -f /run/mysqld/mysqld.pid ]" ]
        interval: 5s
        timeout: 1s
        retries: 1
        
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080


# common variables
